### ISSUE TITLE
Supporting multiple proxies failover?

### ISSUE THREAD

**Issue by yellowsoar** [emarock/proxy-pac-proxy#6]
Is proxy-pac-proxy supporting multiple proxies failover?
like this: https://en.wikipedia.org/wiki/Proxy_auto-config#Advanced_functionality
Or example code(from [McAfee](https://kc.mcafee.com/corporate/index?page=content&id=KB67177&pmv=print&glossary=true)):
```javascript
function FindProxyForURL(url, host) {
    if (dnsDomainIs(host, ".company.com")\ | \ | isInNet(host, "10.1.1.0", "255.255.255.0")\ | \ | isInNet(host, "192.168.1.0", "255.255.255.0"))
        return "DIRECT";
    else if (isInNet(myIPAddress(), "10.1.1.0", "255.255.255.0"))
        return "PROXY proxy01.company.com:9090; proxy02.company.com:9090";
    else
        return "PROXY proxy03.company.com:9090; proxy02.company.com:9090";
}
```

And thanks for your work. Saving my day!

**Comment by emarock** [comment]
Proxy resolution happens here: https://github.com/emarock/proxy-pac-proxy/blob/41b63601540352f104a8157ccc96a50448fb846b/lib/pac/resolver.js#L52 

At the moment the logic is dumb: if it's not DIRECT, the first proxy in the returned list is picked. Changing it to random or round-robin load balancing should be trivial; transparent failover would be a totally different story, probably not worth the effort for the use I've observed people do of this tool. Do you have any particular use case where fail-over would be critical?

**Comment by yellowsoar** [comment]
That totally make sense! Failover is a feature in pac while multiple proxies returns. But proxy-pac-proxy is a proxy service, not a pac file. So, case closed! And my use case is about to handling at least 50 websites between 3 proxies and 7 networks with just one pac file. Without supporting failover like pac does, I have to do a lot work on pac rules instead of just let failover do the magic. But...C'est la vie! XDDD
